<?php
// Do not edit this file - it is automatically generated by InScript

function inscript_hook_the_date ($text)
{
  return inscript_filter ($text, 'the_date');
}

add_filter ('the_date', 'inscript_hook_the_date', 1);

function inscript_hookend_the_date ($text)
{
  return inscript_filter_cache ($text);
}

add_filter ('the_date', 'inscript_hookend_the_date', 10);

function inscript_hook_the_time ($text)
{
  return inscript_filter ($text, 'the_time');
}

add_filter ('the_time', 'inscript_hook_the_time', 1);

function inscript_hookend_the_time ($text)
{
  return inscript_filter_cache ($text);
}

add_filter ('the_time', 'inscript_hookend_the_time', 10);

function inscript_hook_option_blogname ($text)
{
  return inscript_filter ($text, 'option_blogname');
}

add_filter ('option_blogname', 'inscript_hook_option_blogname', 1);

function inscript_hookend_option_blogname ($text)
{
  return inscript_filter_cache ($text);
}

add_filter ('option_blogname', 'inscript_hookend_option_blogname', 10);

function inscript_hook_option_blogdescription ($text)
{
  return inscript_filter ($text, 'option_blogdescription');
}

add_filter ('option_blogdescription', 'inscript_hook_option_blogdescription', 1);

function inscript_hookend_option_blogdescription ($text)
{
  return inscript_filter_cache ($text);
}

add_filter ('option_blogdescription', 'inscript_hookend_option_blogdescription', 10);

function inscript_hook_the_content ($text)
{
  return inscript_filter ($text, 'the_content');
}

add_filter ('the_content', 'inscript_hook_the_content', 1);

function inscript_hookend_the_content ($text)
{
  return inscript_filter_cache ($text);
}

add_filter ('the_content', 'inscript_hookend_the_content', 10);

function inscript_hook_wp_head ($text)
{
  echo inscript_filter ($text, 'wp_head');
}

add_action ('wp_head', 'inscript_hook_wp_head', 1);

?>